### ISSUE TITLE
Kibana server is not ready yet

### ISSUE THREAD

**Issue by ben4562002** [dsnslab/NetworkSecurity#10]
助教你好:
我有設定 Virtual Box 的 port forwarding，並嘗試在本機瀏覽器打開 Kibana，但顯示 "Kibana server is not ready yet."，請問我該從哪裡檢查環境是不是有出錯?😭
![image](https://user-images.githubusercontent.com/50920618/95999787-d2259c80-0e68-11eb-91a5-cd1004cd8f20.png)
![image](https://user-images.githubusercontent.com/50920618/95999801-d5b92380-0e68-11eb-9371-953a97048480.png)

( 底下是我 `docker-compose up` 後所觀察到的 messages，不確定是不是有沒設定到的地方 )
![image](https://user-images.githubusercontent.com/50920618/95999753-c8039e00-0e68-11eb-86ce-d86501465780.png)
![image](https://user-images.githubusercontent.com/50920618/95999822-dce03180-0e68-11eb-999d-dc5846c9556f.png)
![image](https://user-images.githubusercontent.com/50920618/95999834-dfdb2200-0e68-11eb-84ad-add3de48b93b.png)

**Comment by david9705** [comment]
You can check docker work or not. If your docker is up, just wait until it ready.

**Comment by ben4562002** [comment]
![image](https://user-images.githubusercontent.com/50920618/96010290-3863ec80-0e74-11eb-8b0f-c056dfcc2354.png)
yeah, I checked the docker, and it seems to run success

**Comment by dsnslab** [comment]
It seems your ELK fail to setup.
You can try to describe your Ubuntu and Windows environment.

**Hint: I guess you should forward all the ports
you can use ```docker container ls``` to list all containers.**

**Comment by ben4562002** [comment]
That's too bad:(( 
My ubuntu environment is Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-121-generic x86_64), and
Windows10 64-bits
Here are all the containers I have.
![image](https://user-images.githubusercontent.com/50920618/96014164-a3afbd80-0e78-11eb-9198-7794e3ef58cd.png)
and I forward all the ports as below
![image](https://user-images.githubusercontent.com/50920618/96015193-ddcd8f00-0e79-11eb-8e31-9e9b810b10a0.png)

**Comment by dsnslab** [comment]
I found something interesting that your SSH forwarding IP is **different** from others.
I have to make sure your **network configuration**.
Maybe you can describe as below.
- Windows IP: x.x.x.x
- Ubuntu IP: x.x.x.x

**Comment by ben4562002** [comment]
ohh, that's interesting
- Windows IP: 192.168.0.129 (wifi network)
- Ubuntu IP: 
![image](https://user-images.githubusercontent.com/50920618/96016369-3e110080-0e7b-11eb-8918-e7833130e085.png)

**Comment by dsnslab** [comment]
Here is some useful information about **[port forwarding](https://www.kjnotes.com/devtools/77)**.

**Hint: Client IP should be enp0s3**

**Comment by ben4562002** [comment]
yeah, I set up my Client IP as enp0s3, but it still not work:(

**Comment by dsnslab** [comment]
Hi, 
We want to know that how long have you tried to wait after docker-compose up.
If your device isn't powerful enough, it may take certain time to wait for the nodes to be ready.
(p.s. While you are waiting, you can check whether the nodes is still alive using `sudo docker ps -a` from time to time)

**Comment by david9705** [comment]
Do you increase the virtual memory limit by `sudo sysctl -w vm.max_map_count =262144` after you reboot VM **every time**?

**Comment by ben4562002** [comment]
ohh, I found that the node will exit soon, I'm not sure it's correct or not. Should I keep waiting for the Kibana or just kill it and set it correct?
![image](https://user-images.githubusercontent.com/50920618/96085639-ab607800-0ef3-11eb-8900-90408141d463.png)
And I do the `sysctl -w vm.max_map_count =262144` this time when I reboot my VM

**Comment by lilychou0105** [comment]
Same problem over here, but my host IP is different (I'm using VirtualBox for Ubuntu Server)
![image](https://user-images.githubusercontent.com/72923437/96121104-28a2e180-0f22-11eb-85ad-4867d84650e1.png)
When I enter `sudo docker-compose up `, I have same messages as you show above, and it just keep showing up the same message of Kidana and Logstash with different time again and again. It this different from those who had succeed in this part?

**Comment by dsnslab** [comment]
@lilychou0105 
Maybe you can `ping 10.0.2.15` to make sure your network configuration.

**Comment by lilychou0105** [comment]
I had ping 192.168.56.1 in my Windows system and reverse , it's work. But can't ping 10.0.2.15 in my Windows system. However, I used port forwarding in VirtualBox, so if this should be 192.168.56.1 that can work?

**Comment by dsnslab** [comment]
Actually, your should be able to `ping <UbuntuIP>`  in windows.

**Comment by lilychou0105** [comment]
Hi, I have solve the **Kibana not ready** problem!!
I kill my Ubuntu in VirtualBox XD and recreate again
I think the different part is the installation of `docker-compose` .
I install python3-pip than `pip install docker-compose` than` install docker-compose`
Than!! It finally show the login page~~
**But** Now I have problem login with user:admin pwd:admin
and there's not a lot information about this error QQ still working
_I reboot Ubuntu than it can login finally_

**Comment by dsnslab** [comment]
@ben4562002 You should `docker-compose down -v` to kill it.
And then `docker-compose up`.

**Comment by dsnslab** [comment]
@lilychou0105 Congratulations!
So your new problem is can't login with `user:admin pwd:admin`?

**Comment by lilychou0105** [comment]
This has been solved.
_An error occurred while checking your credentials, make sure you have an Elasticsearch cluster secured by Security running_
This is the error when i try to login with `user:admin pwd:admin`, however I can't find some useful solution and advice on Google.
Therefore, I reboot my Ubuntu server, than somehow it can login XD
I'm still working on ping problem that I can't ping 10.0.2.15 on my Windows, so I can't sent the beats to Kibana QQ

**Comment by dsnslab** [comment]
@lilychou0105 
I'm glad to see you solve the problem successfully!
I've already post some useful information about **port forwarding**.
You can find in here.

> Here is some useful information about **[port forwarding](https://www.kjnotes.com/devtools/77)**.

**Comment by NobelNelson** [comment]
@lilychou0105 

yout install docker-compose is to do what the keying code?

**Comment by lilychou0105** [comment]
@NobelNelson  I don't really understand your question QQ
