### ISSUE TITLE
"feilds.hostname" attribute is still unknown

### ISSUE THREAD

**Issue by chiha8888** [dsnslab/NetworkSecurity#16]
I tried this, but "feilds.hostname" attribute in Kibana is still unknown.   
What is the problem?   

![image](https://user-images.githubusercontent.com/26405508/96415788-a700cb80-1221-11eb-83e6-94397835beb4.png)

**Comment by lilychou0105** [comment]
You can see #8

**Comment by chiha8888** [comment]
I also tried  
``` fields.hostname: "_XXXXXXX" ```  
but not work.

**Comment by jehoshuapratama** [comment]
You could also configure it via logstash configuration. Which is located in the elastic/pipeline/logstash.conf.

**Comment by dsnslab** [comment]
@chiha8888 
Your hostname should be lower case and make sure you restart your winlogbeat.

**Comment by chiha8888** [comment]
I did restart my winlogbeat.  

But with this line of code, it still not works.  
![image](https://i.imgur.com/N9klQQm.png)

**Comment by dsnslab** [comment]
@chiha8888 You should not write `fields.hostname` directly.
Your format should be as same as below.
You should be able to **create new index** without unknown.


> ![image](https://user-images.githubusercontent.com/26405508/96415788-a700cb80-1221-11eb-83e6-94397835beb4.png)

**Comment by chiha8888** [comment]
Oh, it works after I change index pattern from logstash* to logstash-*  
Thanks
