### ISSUE TITLE
invalid argument

### ISSUE THREAD

**Issue by Leon777-coder** [dsnslab/NetworkSecurity#18]
I did the step that TA ask me to do(sudo docker system/volume prune ,         then try sudo docker-compose up again), however even the first 2 successes,  it still tells me that I have invalid argument for sudo docker-compose up
![invalid](https://user-images.githubusercontent.com/69491904/96469362-b4d54180-125f-11eb-8309-34ed1d83a6bf.PNG)

**Comment by NobelNelson** [comment]
用這個看看 sudo apt-get update

**Comment by Leon777-coder** [comment]
same result, still invalid argument..
and I believe I've already try this code before...the sudo apt-get update
![invalid](https://user-images.githubusercontent.com/69491904/96470883-54470400-1261-11eb-9cb0-8106e63f2d7e.PNG)

**Comment by dsnslab** [comment]
Maybe you can try [this](https://stackoverflow.com/questions/55334380/error-readlink-var-lib-docker-overlay2-invalid-argument).

**Comment by dsnslab** [comment]
Hi,
You forgot to add --all in the first command.
`docker system prune --all`
Please try to run the three commands again.

**Comment by Leon777-coder** [comment]
i guess it works now, thanks for your helping. what a Silly mistake....
![invalid](https://user-images.githubusercontent.com/69491904/96479418-83fb0980-126b-11eb-8850-e88ca1550a9a.PNG)

**Comment by NobelNelson** [comment]
so,use this docker system prune --all is the solution?

**Comment by Leon777-coder** [comment]
well, i enter the docker system prune --all, then it say it will clean some images, based on the site that TA said, I guess this is the only solution to solve this. And after I clean they I ran docker-compose up, then my terminal become like this(it just keep running and running) and I guess this is what it should be, yeah?
![invalid](https://user-images.githubusercontent.com/69491904/96488720-04703900-1271-11eb-90d6-c423499625bf.PNG)

however even I finished all the process, and I tried to connect to the kibana with my ip,but it still denied me. 
![invalid2](https://user-images.githubusercontent.com/69491904/96488937-53b66980-1271-11eb-8d64-29c328d4dbbf.PNG)

**Comment by dsnslab** [comment]
I think there are still some problems with ELK.
Maybe you can provide docker container status, so we will know containers are still alive.
Also, you can provide your network configuration such as `ipconfig` in windows and `ifconfig` in ELK.

**Comment by lilychou0105** [comment]
@Leon777-coder **Here's a reminder.**
I use Virtual-Box as well, and I found out that there might be some problem with memory.
The default set up of virtual hard disk(?) is 10 GB.
However, that's not enough! Installation of all required packet will take around that.
So there's no space to build up Kibana.
I increase it to 40 GB XD Then,  it run smoothly.

**Comment by Leon777-coder** [comment]
> @Leon777-coder **Here's a reminder.**
> I use Virtual-Box as well, and I found out that there might be some problem with memory.
> The default set up of virtual hard disk(?) is 10 GB.
> However, that's not enough! Installation of all required packet will take around that.
> So there's no space to build up Kibana.
> I increase it to 40 GB XD Then, it run smoothly.

I am pretty sure I set yo my space more than 40GB tho when I build this VM, but still thanks for your comment
