### ISSUE TITLE
what the meaning of got permission denied when I check docker version

### ISSUE THREAD

**Issue by NobelNelson** [dsnslab/NetworkSecurity#19]
![image](https://user-images.githubusercontent.com/72659729/96488166-2a490e00-1270-11eb-9770-62e1fc036e30.png)
It means docker is not work?
what can I fix it?

**Comment by dsnslab** [comment]
You should type `sudo docker version` instead.
In fact, you can google error message directly and you will get the answer.

**Comment by Leon777-coder** [comment]
I think u made the same mistake I made earlier, u should type sudo to give the root permission
