### ISSUE TITLE
error fetching fields for index pattern winlogbeat: Not Found

### ISSUE THREAD

**Issue by henry88521** [dsnslab/NetworkSecurity#20]
不知道有沒有人跟我遇到一樣的問題
![問題](https://user-images.githubusercontent.com/41564555/96557730-3b843000-12ed-11eb-9a9e-3fb8019a6005.PNG)
已經好幾個小時卡在這了
winlogbeat就照著官網改，然後改用logstash連線
start-service winlogbeat之後在kibana上怎麼跑都一樣

唯一想到可能的bug是官網說要連至logstash下這條
.\winlogbeat.exe setup --template -E output.logstash.enabled=false -E 'output.elasticsearch.hosts=["192.168.153.133:9200"]'
可是他只會噴
![問題2](https://user-images.githubusercontent.com/41564555/96558586-7c307900-12ee-11eb-8f26-d4fd14cc65f9.PNG)
而且我做完的朋友跟我說不用下 .\winlogbeat setup的指令(?)

**Comment by dsnslab** [comment]
Hi, 
You've used the wrong index pattern. Please go to the "create index pattern" to see which pattern you should use. You can refer to #16.
For the winlogbeat, you can use `.\winlogbeat.exe -e` to run it.
