### ISSUE TITLE
Weird  host name

### ISSUE THREAD

**Issue by Leon777-coder** [dsnslab/NetworkSecurity#22]
After the change of host_id, seems like it didn't work and it still only have 236617..i already change my id in the winlogbeat.yml tho, and actually this number -236617 doesn't even exist in this yml file nor any other file...

![invalid](https://user-images.githubusercontent.com/69491904/96580757-59f92400-130b-11eb-9e3a-587cb21d027d.PNG)

**Comment by dsnslab** [comment]
Hi,
Please screenshot the log in this index pattern.
We want to make sure that you have uploaded the lastest log.
If your latest log is still hostname:236617, you can use those logs to finish your project 1.
But please screenshot the part of the winlogbeat.yml where you changed your fields.hostname and explain that you have this situation in the report.

**Comment by scott870430** [comment]
Is your host_id meaning the host_id of fields in winlogbeat.yml?
Maybe you should try to change hostname?

**Comment by Leon777-coder** [comment]
> Hi,
> Please screenshot the log in this index pattern.
 hi TA 
is this what u meant?
![invalid](https://user-images.githubusercontent.com/69491904/96585242-e0b0ff80-1311-11eb-9c3b-25e303b4a69c.PNG)

**Comment by Leon777-coder** [comment]
> Is your host_id meaning the host_id of fields in winlogbeat.yml?
> Maybe you should try to change hostname?

hello, I mention it in the wrong way. yes I change the host name in my yml file, I put my Id on it. But idk why it ends up like this

**Comment by dsnslab** [comment]
@Leon777-coder 
No, I meant the content after you create the index.

**Comment by Leon777-coder** [comment]
> @Leon777-coder
> No, I meant the content after you create the index.


this is what I got after I use this index
![invalid](https://user-images.githubusercontent.com/69491904/96585928-d80cf900-1312-11eb-962c-d112e15b2624.PNG)

**Comment by Leon777-coder** [comment]
> @Leon777-coder
> No, I meant the content after you create the index.
  


this is what I got after selecting this 236617 index
![invalid](https://user-images.githubusercontent.com/69491904/96586160-2d490a80-1313-11eb-837e-34233272fdf2.PNG)

**Comment by scott870430** [comment]
Have you tried to log in again in Kibana or restart the winlogbeat via **Stop-Service winlogbeat**?

**Comment by Leon777-coder** [comment]
> Have you tried to log in again in Kibana or restart the winlogbeat via **Stop-Service winlogbeat**?

Yes I did re-log in the kibana, and nothing changed, actually I don't even know where these number comes from

**Comment by Leon777-coder** [comment]
> @Leon777-coder
> No, I meant the content after you create the index.



sorry sir, this is the correct one, the field.hostname is 236.617
![invalid](https://user-images.githubusercontent.com/69491904/96588131-d6910000-1315-11eb-9579-306d334e7f10.JPG)

**Comment by Shoot-to-root** [comment]
Can u screenshot your winlogbeat.yml? Just the hostname field will be sufficient.

**Comment by Leon777-coder** [comment]
> Can u screenshot your winlogbeat.yml? Just the hostname field.

here, as u can see i change my hostname into my school ID

![host](https://user-images.githubusercontent.com/69491904/96589216-20c6b100-1317-11eb-9bc1-af297eb8e683.JPG)

**Comment by Shoot-to-root** [comment]
> 
> 
> > Can u screenshot your winlogbeat.yml? Just the hostname field.
> 
> here, as u can see i change my hostname into my school ID
> 
> ![host](https://user-images.githubusercontent.com/69491904/96589216-20c6b100-1317-11eb-9bc1-af297eb8e683.JPG)

u have to add an underscore before your id. E.g. hostname: "_0716111"

**Comment by Leon777-coder** [comment]
> > > Can u screenshot your winlogbeat.yml? Just the hostname field.
> > 
> > 
> > here, as u can see i change my hostname into my school ID
> > ![host](https://user-images.githubusercontent.com/69491904/96589216-20c6b100-1317-11eb-9bc1-af297eb8e683.JPG)
> 
> u have to add an underscore before your id. E.g. hostname: "_0716111"


hi thanks for ur replay
I did what u say, and also restart the PowerShell and Kibana. Unfortunately nothing changed

**Comment by Shoot-to-root** [comment]
> 
> 
> > > > Can u screenshot your winlogbeat.yml? Just the hostname field.
> > > 
> > > 
> > > here, as u can see i change my hostname into my school ID
> > > ![host](https://user-images.githubusercontent.com/69491904/96589216-20c6b100-1317-11eb-9bc1-af297eb8e683.JPG)
> > 
> > 
> > u have to add an underscore before your id. E.g. hostname: "_0716111"
> 
> hi thanks for ur replay
> I did what u say, and also restart the PowerShell and Kibana. Unfortunately nothing changed

Try removing the double quote around the hostname? Like this: hostname: _0716111

**Comment by Leon777-coder** [comment]
> > > > > Can u screenshot your winlogbeat.yml? Just the hostname field.
> > > > 
> > > > 
> > > > here, as u can see i change my hostname into my school ID
> > > > ![host](https://user-images.githubusercontent.com/69491904/96589216-20c6b100-1317-11eb-9bc1-af297eb8e683.JPG)
> > > 
> > > 
> > > u have to add an underscore before your id. E.g. hostname: "_0716111"
> > 
> > 
> > hi thanks for ur replay
> > I did what u say, and also restart the PowerShell and Kibana. Unfortunately nothing changed
> 
> Try removing the double quote around the hostname? Like this: hostname: _0716111

Still doesn't work

**Comment by Shoot-to-root** [comment]
![image](https://user-images.githubusercontent.com/36467319/96592805-5d94a700-131b-11eb-9489-47c6485bea3d.png)
Try this?

**Comment by Leon777-coder** [comment]
> ![image](https://user-images.githubusercontent.com/36467319/96592805-5d94a700-131b-11eb-9489-47c6485bea3d.png)
> Try moving it right under "fields:"?

still doesn't work

**Comment by dsnslab** [comment]
> > @Leon777-coder
> > No, I meant the content after you create the index.
> 
> sorry sir, this is the correct one, the field.hostname is 236.617
> ![invalid](https://user-images.githubusercontent.com/69491904/96588131-d6910000-1315-11eb-9579-306d334e7f10.JPG)

HI,
Quotes should be OK
The log upload time is this afternoon. 
Is that possible that you haven't successfully uploaded any new log after the TA hour?

**Comment by Leon777-coder** [comment]
> Is that possible that you haven't successfully uploaded new log after the TA hour?
well after I set the time range into 5 hours before to now, yeah there is no data appear neither  logstash-236617.unknwn nor logstash-unknown.unknown, so maybe this make sense?...but all my tool run fine so I don't know why tho
![in](https://user-images.githubusercontent.com/69491904/96594486-3fc84180-131d-11eb-9f77-32046a01dfc3.JPG)

**Comment by Leon777-coder** [comment]
> > > @Leon777-coder
> > > No, I meant the content after you create the index.
> > 
> > 
> > sorry sir, this is the correct one, the field.hostname is 236.617
> > ![invalid](https://user-images.githubusercontent.com/69491904/96588131-d6910000-1315-11eb-9579-306d334e7f10.JPG)
> 
> HI,
> Quotes should be OK
> The log upload time is this afternoon.
> Is that possible that you haven't successfully uploaded any new log after the TA hour?

is this the reason why it's fail to send any log after the TA hour? i found it in my powershell, and it keep appearing. 
![in](https://user-images.githubusercontent.com/69491904/96599243-4dcc9100-1322-11eb-94a5-2aee94ac5a62.JPG)
