### ISSUE TITLE
Training Data & Test Data

### ISSUE THREAD

**Issue by chen870914** [dsnslab/NetworkSecurity#23]
PDF上面似乎沒有說明哪個data對應到哪種攻擊，但是這樣我在做test的時候就沒辦法確定我的model判斷的是否準確。
想請問助教能否提供這方面的資訊，謝謝。

**Comment by SnowWhite1129** [comment]
In the spec, 4.1.b 
The testing samples we provided(Test 1, Test 2) are the corresponding sets for Training data(Attack 1, Attack 2)

**Comment by dsnslab** [comment]
In the spec, 4.1.b
The testing samples we provided(Test 1, Test 2) are the corresponding sets for Training data(Attack 1, Attack 2)
