### ISSUE TITLE
Input Format Problem

### ISSUE THREAD

**Issue by rreexxllii0310** [dsnslab/NetworkSecurity#25]
How can I get input <PATH> from command `python3 mycode.py <PATH>`?
I google it, but all of the results are using input() or raw_input() from command after running  `python3 mycode.py`.
![image](https://user-images.githubusercontent.com/40860137/100910096-74c4d800-3508-11eb-9d26-2d49e75bbfac.png)

How can I get input when I run `python3 mycode.py <PATH>` at same time without typing input on command again?
![image](https://user-images.githubusercontent.com/40860137/100910051-68d91600-3508-11eb-856d-1e7dc45c3cea.png)

Thank,you!

**Comment by aesophor** [comment]
I think `input()` and `raw_input()` are used for reading input from **stdin**,
maybe `open()` is what you're looking for (it allows you to open a file and read its content).

https://www.w3schools.com/python/python_file_open.asp

**Comment by apple11361** [comment]
You can use `sys.argv` to get the \<PATH\>. 
This is the tutorial, [[How to use sys.argv in Python](https://www.knowledgehut.com/blog/programming/sys-argv-python-examples)].
After that, as @aesophor said, maybe `open()` is the choice.

**Comment by joydec1118** [comment]
you can refer to this.

https://ithelp.ithome.com.tw/articles/10215998

**Comment by rreexxllii0310** [comment]
Thanks everyone!

**Comment by NobelNelson** [comment]
![image](https://user-images.githubusercontent.com/72659729/102012453-69ce3b00-3d85-11eb-8e18-c64c112be28a.png)
why is the lamda doing?

**Comment by aesophor** [comment]
@NobelNelson  You can ignore it. It's called a "shell prompt" (defined by $PS1)

https://www.cyberciti.biz/tips/howto-linux-unix-bash-shell-setup-prompt.html
