### ISSUE TITLE
import json to ES

### ISSUE THREAD

**Issue by chiha8888** [dsnslab/NetworkSecurity#27]
I can't import json file to ES using elasticdump, it keeps showing socket hang up error.   
What did I do wrong?  
(I'm using the ES given by TA in HW01)  

![png](https://i.imgur.com/9beg6uK.png)  

![png](https://i.imgur.com/PxqmsoN.png)

**Comment by SnowWhite1129** [comment]
Same problem as #24 .

**Comment by VaTanJo** [comment]
Your ElasticSearch is http**s**, NOT http
and you have to send the name:passwd in your command 
you can see [Elasticdump](https://github.com/elasticsearch-dump/elasticsearch-dump), there are more details
