### ISSUE TITLE
Hint by TA

### ISSUE THREAD

**Issue by dsnslab** [dsnslab/NetworkSecurity#31]
# Test4 case
- We provided an additional test case for Attack4 in newe3 platform, it has more obvious behavior in it.

# Elasticdump problem
- You can refer to #24, they have some possible solutions

# Output
- For the output, you only need to output Attack_ID. You don't need to output the attack name. 

# Format issue
- About the format issue, always follow the spec.

# Notice
- Make sure you have read old(closed) issue before you post issues.
- We might directly close the issue if it is a duplicate problem.

**Comment by aesophor** [comment]
If we should output Attack_ID, the ID should correspond to the order of attacks listed in the spec, right?

I mean:
* Attack_1 = Port Scan
* Attack_2 = SQL Injection
* Attack_3 = Brute-Force Attack
* Attack_4 = DDoS
* Attack_5 = Phishing Email

<br>

<img width="604" alt="Screen Shot 2020-12-13 at 2 37 44 PM" src="https://user-images.githubusercontent.com/32998585/102005042-c82cf680-3d50-11eb-9991-427f6a14d90b.png">

**Comment by dsnslab** [comment]
Hi, 
No, You should output the Attack ID which is corresponding to the training data.

**Comment by aesophor** [comment]
Thanks
