### ISSUE TITLE
The DEMO testcase has 5 files,too?

### ISSUE THREAD

**Issue by a4865g** [dsnslab/NetworkSecurity#32]
As title,

and will each attack appear exactly once?

Thanks!

**Comment by dsnslab** [comment]
Hi 
About first question. Do you mean 5 test cases? If yes, then no. There will be new test cases and test cases we have given you. 
And for the second question, we will not disclose the content of the demo data.

**Comment by a4865g** [comment]
Ok, thanks for your reply!
