### ISSUE TITLE
How to read test data in efficient?

### ISSUE THREAD

**Issue by rreexxllii0310** [dsnslab/NetworkSecurity#36]
As title,
I tyied to use `pd.read_json(json_file,lines=True)`, but it raise Memory error
because I need to extract key,value from the json_file
so, I used `json.loads(line)` (line is one line in json_file) to read one by one, and extract the key/value I need.
it work, but I found it too slow to read(40k lines/5 mins).

Is there any better way to read?
thanks!

**Comment by LexCC** [comment]
I have encountered the same issue. FYI, my solution is to reduce the time by multiprocessing.

``jobs = [ multiprocessing.Process(target=parse_packetjson, args=(pd.read_json('./Train/Attack_'+str(i)+'/packetbeat.json', lines=True),'attack '+str(i))) for i in range(1,6) ]``

**Comment by rreexxllii0310** [comment]
Thank you, I will try it.

**Comment by Shoot-to-root** [comment]
I'm wondering how to read the training data in more efficiently? It takes hours to load all of them. Can someone enlighten me?

**Comment by dsnslab** [comment]
Closed as no further discussion
