### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by chiao0121** [dsnslab/NetworkSecurity#4]
### **Question about Winlogbeat & Packetbeat**

- When I tried to start `.\winlogbeat.exe setup -e` & `.\packetbeat.exe setup -e` in Powershell (select run as Administrator), I would get an error message. (**_"error connecting to Elasticsearch at http://ubuntu_id:9200"_**)  I can't find new log in Kibana so I guess the reason behind is this issue. Does any suggestion for this issue??

- I tried to use `ping` (windows->linux & linux->windows) to check and I found only linux can ping to windows.  I got a research about this issue and they said Network setup of NAT that they can't ping to each other. But using the Bridge, they can ping to each other.

**Comment by nelson870708** [comment]
1. run .\winlogbeat setup --dashboards, not .\winlogbeat.exe setup -e
2. You can try port forwarding

**Comment by NobelNelson** [comment]
![image](https://user-images.githubusercontent.com/72659729/95669151-ce1b2580-0baf-11eb-8a1d-63752e017298.png)
using this .\winlogbeat setup --dashboards
it has the same problem

**Comment by nelson870708** [comment]
@NobelNelson 

It seems that your terminal in Windows can't find the Kibana server. 
Check the following problems:
1. Do you set up your ELK stack environment?
2. Can your terminal in Windows pings your Ubuntu environment?

**Comment by NobelNelson** [comment]
@nelson870708 
![image](https://user-images.githubusercontent.com/72659729/95673852-db9bd400-0bde-11eb-9d04-362f2ce1fc0e.png)
I run the sudo docker compose up
Is this meaning  ELK stack environment is ok?
And,how can I do some action to terminal in Windows pings Ubuntu environment?

**Comment by nelson870708** [comment]
@nelson870708 

Your ELK stack environment is now set up.
Just as TA says, you can try port forwarding.
It is not able to show all the step to do port forwarding, but I hope the website bellow will help: 
[https://www.kjnotes.com/devtools/77](url)
In addtion, you should forward to the port 5044 for Logstash and the port 5601 for Kibana.
