### ISSUE TITLE
Windows VM keeps restarting again and again

### ISSUE THREAD

**Issue by crystal0523** [dsnslab/NetworkSecurity#40]
Hi TA, I would like to ask the Question of environment:
I used the VM released by TA, but it turned out that whenever I started up the Windows VM, the machine just kept lagging and restarting itself again and again. So I'm wondering if it's OK for me to install a Windows 10 VM by myself? Or there is some configuration already setted up in the one released by TA., thank you.

**Comment by dsnslab** [comment]
The problem might be your computer's memory is not enough. We suggest you to use the computer with at least 12G.
It's ok for you to use Windows 10 VM by yourself. Make sure you are using the Win10 Pro edition, cause some of the logs can't be found in the others editions.
You only have to make sure the two VM can connect to each other.
