### ISSUE TITLE
winlogbeat config setup

### ISSUE THREAD

**Issue by angusyang1130** [dsnslab/NetworkSecurity#42]
Hi TA, 
    I have two questions to ask:
       1. I want to set up the configuration of the winlogbeat and I am on step 3, but it says "more than one configured accessing 
           output, what is the problem I might have met?
       2. Is the elastic.zip file need to be launched on the Ubuntu VM? If so, I am not sure how to install the docker first before 
           docker-compose up
![2021-03-24 (2)](https://user-images.githubusercontent.com/73729785/112264584-10db4080-8cac-11eb-863e-a8b202e84133.png)
![2021-03-24 (3)](https://user-images.githubusercontent.com/73729785/112264590-120c6d80-8cac-11eb-9873-3bb650d0babb.png)

**Comment by Smileyezzz** [comment]
1. Maybe you can get some hints from the reference below. They are the others environment issues before.
Try to figure out what the output meaning in the winlogbeat.yml, we also supply the official document about the output of winlogbeat below. 
Github Issue : https://github.com/dsnslab/NetworkSecurity/issues/41
Logstash-output: https://www.elastic.co/guide/en/beats/winlogbeat/current/logstash-output.html
Elasticsearch-output: https://www.elastic.co/guide/en/beats/winlogbeat/current/elasticsearch-output.html

2. The error seem to be permission error. Add the 'sudo' before the docker command. 
Please check if there are 4 containers under your Ubuntu VM. You can check it with 'docker ps -a' command. If there is permission error, then you should add 'sudo'. 
If there are actually 4 containers under your Ubuntu VM, just run 'docker-compose up'.

**Comment by dsnslab** [comment]
1. Maybe you can get some hints from the reference below. They are the others environment issues before.
Try to figure out what the output meaning in the winlogbeat.yml, we also supply the official document about the output of winlogbeat below.
Github Issue : #41
Logstash-output: https://www.elastic.co/guide/en/beats/winlogbeat/current/logstash-output.html
Elasticsearch-output: https://www.elastic.co/guide/en/beats/winlogbeat/current/elasticsearch-output.html

2. The error seem to be permission error. Add the 'sudo' before the docker command.
Please check if there are 4 containers under your Ubuntu VM. You can check it with 'docker ps -a' command. If there is permission error, then you should add 'sudo'.
If there are actually 4 containers under your Ubuntu VM, just run 'docker-compose up'.

**Comment by crystal0523** [comment]
I have the question of winlogbeat setting to:
![q](https://user-images.githubusercontent.com/24898062/112453009-32aef300-8d92-11eb-8f83-c2ad326c4bcd.png)
 I have modifed the winlogbeat.yml file, but still get these errors.

**Comment by crystal0523** [comment]
Hi, TA,
I have the same question of winlogbeat setting:
After I run  ``` PowerShell.exe -ExecutionPolicy UnRestricted -File .\install-service-winlogbeat.ps1.  ``` , the system show:
Status      : Stopped
Name        : winlogbeat
DisplayName : winlogbeat
But when I started to run  ```  .\winlogbeat.exe setup -e```  , it shows up the error message:
![q](https://user-images.githubusercontent.com/24898062/112455828-0ba5f080-8d95-11eb-8c80-bbaf9a73e257.png)
I'm wondering if there's something I missed? thanks!

**Comment by dsnslab** [comment]
The message shown after `PowerShell.exe -ExecutionPolicy UnRestricted -File .\install-service-winlogbeat.ps1` means that you've already installed the service, but haven't started yet.

For installing winlogbeat, please refer to [this response](https://github.com/dsnslab/NetworkSecurity/issues/37#issuecomment-799232096).

Besides, the error message in the screenshot seems not to be `.\winlogbeat.exe setup -e` as you mentioned.

**Comment by crystal0523** [comment]
But I just cannot started the service, error message is shown in pic. I have searched for a lot of information in Google, just can't figure out what's going on.
<img width="554" alt="q1" src="https://user-images.githubusercontent.com/24898062/112491847-ad403880-8dbb-11eb-8d2f-09281f317100.png">

**Comment by angusyang1130** [comment]
Hi TA, 
    I have figured the previous problem, but now my question is:
        Do I have to download kibana on my host machine (I didn't use the window VM you have provided), or the website could 
        be set up through the Ubuntu VM (I have done port forwarding)?

**Comment by angusyang1130** [comment]
Hi TA,
I think I have figured out the previous problem, but now I have some questions about kibana:
1. I am on the step to set up the dashboard to kibana by powershell, but it says the version is not right or something like that, I am not sure how to solve it
2.  I think I have gotten into the kibana website, but I am not sure if the setting is right, and I didn't receive any log yet ( it says error)
![2021-03-26 (2)](https://user-images.githubusercontent.com/73729785/112610434-a5ce6d00-8e57-11eb-9546-1173269346b5.png)
![2021-03-26 (3)](https://user-images.githubusercontent.com/73729785/112610441-a7983080-8e57-11eb-8223-d2f2ed568752.png)

**Comment by dsnslab** [comment]
Hi. 
You do not need to set up the dashboard to kibana from Powershell.
You could ignore this step and try to start the service directly.

**Comment by angusyang1130** [comment]
Thank you TA, but now when I type in "Start-Service winlogbeat", it says could not find the service, is there anything I might do wrong during the configuration? 
![2021-03-26 (5)](https://user-images.githubusercontent.com/73729785/112634265-5bf47f80-8e75-11eb-80c7-ab1938af8de0.png)

**Comment by dsnslab** [comment]
@angusyang1130, looks like you forgot to install the service first.

**Comment by angusyang1130** [comment]
Hi TA, 
Right, I did not notice that, thank you for pointing out. Right now I am trying to debug the configuration of winlogbeat service( the command "./winlogbeat -e", but there are some errors, it says there are some problems on the dashboard and kibana version, I am not sure how to solve it.
![2021-03-29 (3)](https://user-images.githubusercontent.com/73729785/112845290-48485380-90d7-11eb-9406-51d7e0a4366f.png)

**Comment by dsnslab** [comment]
Please refer to #37.
The [question](https://github.com/dsnslab/NetworkSecurity/issues/37#issuecomment-799193337) and the [response](https://github.com/dsnslab/NetworkSecurity/issues/37#issuecomment-799232096) may help.

Feel free to ask if other problems still exist.

**Comment by angusyang1130** [comment]
Hi TA, 
I have looked at #37, but I have already commented the setting of output.elasticsearch, should I do something do something else?

**Comment by dsnslab** [comment]
Please verify that the error originates from `winlogbeat -e`.
The screenshot you posted looks similar to the output of `winlogbeat setup -e`

Did you remember to uncomment output.logstash as well?

**Comment by angusyang1130** [comment]
Hi TA, 
here are screenshots of powershell and winlogbeat.yml
![2021-03-29 (6)](https://user-images.githubusercontent.com/73729785/112858528-89933000-90e4-11eb-9d40-f1cc4570e3ec.png)
![2021-03-29 (8)](https://user-images.githubusercontent.com/73729785/112858540-8b5cf380-90e4-11eb-8617-ccbea5978117.png)

**Comment by dsnslab** [comment]
It seems that your winlogbeat is still trying to set up the dashboard on the Kibana. 
Please check if you set the `setup.dashboards.enabled` to true in your configuration file.
This option should be commented out or be set to false.

If the problem still exists, you could try to get a clean `winlogbeat.example.yml` and only re-config the necessary settings.

**Comment by angusyang1130** [comment]
HI TA, 
Yes, I did set it to true, I can get the winlogbeat logs now, but may I ask that is screen savor dismiss means to set up in group policy "stop screen saver" or just set the screen saver to "close" from the computer
![2021-03-30 (3)](https://user-images.githubusercontent.com/73729785/112969568-f0b1f280-917f-11eb-847f-538c2fb09fba.png)
