### ISSUE TITLE
group policy editor problem

### ISSUE THREAD

**Issue by chelseaxdxd** [dsnslab/NetworkSecurity#44]
助教您好，
我看了前面group policy setting的問題後有照著助教給的方向改動Audit Policy, 如此圖上方已經換成success,Failure
但是我還是收不到相應的log資料 ex.logon success(4624) 
![image](https://user-images.githubusercontent.com/43904738/112746639-ae9f7a00-8fe2-11eb-90eb-a505e6ebda31.png)

上網查了資料不確定是否需要用到Group Policy Management來額外做設定，但是因為電腦是workgroup所以沒辦法使用，
想請問我現在的方向是對的嗎？

**Comment by afcidk** [comment]
The event viewer seems to be still searching (the lower left corner)

I think logon sucess does not need to configure the group policy. Did you wait until the search process is done?

**Comment by chelseaxdxd** [comment]
有的它跑完顯示沒有找到符合4624的...
還有不只是logon success
其他screen saver , file modify, 關閉.exe檔...等，那些log都沒有抓到耶QQ
但是kibana上面的確有收到那段時間的log
改動的host name也確實符合我yml檔案裡設定的，只是log都沒有作業上需要的那六個event.....
另外想確認一下logon success是windows帳戶登入就會有沒錯吧

**Comment by dsnslab** [comment]
Please provide more information or come at TA hours, or else we cannot figure out the problem with limited information.

> 另外想確認一下logon success是windows帳戶登入就會有沒錯吧

Yes.

**Comment by 789gogogo** [comment]
Hi TAs,
I have problem with downloading group policy editor. I tried these two websites : https://www.itechtics.com/enable-gpedit-windows-10-home/ & https://www.microsoft.com/zh-TW/download/details.aspx?id=48257. As I know, I should right-click the downloaded "gpedit-enabler.bat" file and select "Run as Administrator". When I do so, the installation won't start. 
The picture below is what I will see.
![image](https://user-images.githubusercontent.com/81570111/112841595-4381a080-90d3-11eb-9673-f36e61becfa9.png)
What's wrong with this?

**Comment by dsnslab** [comment]
@789gogogo , please make sure that your Windows is the correct version (Windows 10 x64 Professional)

**Comment by 789gogogo** [comment]
Isn't it fit for Win10 Home?
This is my computer version:
![image](https://user-images.githubusercontent.com/81570111/112850811-eee32300-90dc-11eb-8bc8-c69c8bfb1fcf.png)
![image](https://user-images.githubusercontent.com/81570111/112850863-fdc9d580-90dc-11eb-8f61-48123af9c598.png)
