### ISSUE TITLE
Information about C&C attack

### ISSUE THREAD

**Issue by nagi1999a** [dsnslab/NetworkSecurity#45]
Hello, TAs.
According to ppt, logs for C&C attack is about "**the attacker exfiltrate some files from the victim on an unusual port**", but after some investigation with Kibana, I still could not found lots of information with those packetbeat logs. Is there any further information or tips we can get about the attack? Thanks.

**Comment by dsnslab** [comment]
Firstly you should know exfiltration **might** have some effect on packets. 
Secondly there are some ports in common use. You can filter those ports out and you **might** find an unusual port in the packetbeat logs.

Best, 
TA

**Comment by nagi1999a** [comment]
Thanks for reply, I will try again with suggestions.
