### ISSUE TITLE
import data problem

### ISSUE THREAD

**Issue by yen-junyu** [dsnslab/NetworkSecurity#47]
I try to import data use "official ElasticSearch service" , and I encountered the following problem.

<img width="1429" alt="截圖 2021-05-23 下午2 26 21" src="https://user-images.githubusercontent.com/37117594/119250501-09181980-bbd3-11eb-9098-7b2b819daff1.png">

what setting I miss? 
or I need to change json file by myself to fit the import format?

**Comment by afcidk** [comment]
You have to modify the json file.
Simply remove the `_index`, `_type`, `_id`, `_score` key and `_source` key. 

That is to change
```
{
   "_index":"logstash-netsec.proj2-2021.04.08",
   "_type":"_doc",
   "_id":"KakgsHgBrjaDa8NYk4HG",
   "_score":0,
   "_source":{ ...Only leave the value here... }
}
``` 
to
```
{ ... The value of _source key ... }
```

**Comment by yen-junyu** [comment]
Thanks for reply.
