### ISSUE TITLE
問題，kibana server is not ready yet

### ISSUE THREAD

**Issue by NobelNelson** [dsnslab/NetworkSecurity#6]
![image](https://user-images.githubusercontent.com/72659729/95658569-02f69080-0b4e-11eb-808e-8290695f2880.png)
照著助教的步驟做，在網頁上填上 your_Ubuntu_ IP:5601. ，上面卻跑出kibana server is not ready yet，這問題該如何解決?
還有kibna是這步驟做完就有結果，就可以做作業了，那為甚麼還需要在windows上裝Winlogbeat 和 Packetbeat ?

**Comment by dsnslab** [comment]
You might have to provide detail information.
Maybe you just need to **give it some time**.

Without beats,  logs won't be collected and sent to Kibana.
