### ISSUE TITLE
Question on Kibana

### ISSUE THREAD

**Issue by rreexxllii0310** [dsnslab/NetworkSecurity#8]
請問助教，
1.我發生了圖片右下角的error，請問要怎麼解決呢
![image](https://user-images.githubusercontent.com/40860137/95839695-e3da4780-0d75-11eb-8bc8-0644c486bf1c.png)

2.請問第a和b小題是要從哪裡登入登出呢?
![image](https://user-images.githubusercontent.com/40860137/95840037-44698480-0d76-11eb-8f2a-a8d941241e9c.png)

**Comment by dsnslab** [comment]
1. You can ignore this error unless encountering some problems.
2. You should logon/off in Windows.

**Comment by rreexxllii0310** [comment]
> 1. You can ignore this error unless encountering some problems.
> 2. You should logon/off in Windows.

OK,Thank you~!
Can I ask why my fields.hostname are all unknown?
How to edit it?

**Comment by dsnslab** [comment]
You can refer to closed issue #1.
It might help you.

**Comment by rreexxllii0310** [comment]
OK
1.請問為什麼我開關application還有開啟特定網頁，log上都沒有資訊呢?
![image](https://user-images.githubusercontent.com/40860137/95967473-df2d9600-0e3e-11eb-95d7-1a5863feb665.png)

我看powershell上有Application
![image](https://user-images.githubusercontent.com/40860137/95968387-f325c780-0e3f-11eb-855e-7482b532ea1d.png)

**Comment by dsnslab** [comment]
1. You should check if the specific events exist on the `Event Viewer`
2. You should use `packetbeat` to observe connecting specific website. 

**Hint: You should run beats as `admin`**

**Comment by rreexxllii0310** [comment]
> 1. You should check if the specific events exist on the `Event Viewer`
> 2. You should use `packetbeat` to observe connecting specific website.
> 
> **Hint: You should run beats as `admin`**

I have looked #1 ,but I can't find `secpol.msc` on my computer(windows 10 home), how can I handle it?
I also can't find `gpedit.msc`
-------------------------------------------------------------------------------------------------------------------
How can I track file event using winlogbeat?
Or I need to use filebeat?

**Comment by dsnslab** [comment]
I'm not sure why you have to find `secpol.msc`, but if you want, I found some [information](https://freeingcockatiel.blogspot.com/2016/09/windows10-secpolmsc.html) about it.
It might help you.

You **don't** have to use other beats to complete this project.
Maybe you can try to google `Event Viewer`.
There are some information about windows events, so you will know how to observe the log.

**Comment by rreexxllii0310** [comment]
> I'm not sure why you have to find `secpol.msc`, but if you want, I found some [information](https://freeingcockatiel.blogspot.com/2016/09/windows10-secpolmsc.html) about it.
> It might help you.
> 
> You **don't** have to use other beats to complete this project.
> Maybe you can try to google `Event Viewer`.
> There are some information about windows events, so you will know how to observe the log.

![image](https://user-images.githubusercontent.com/40860137/96006291-e91bbd00-0e6f-11eb-80e4-431e8f49557e.png)

Now I find the create file event on `Event Viewer`
But my kibana  no has log on it, and I don't know why.
![image](https://user-images.githubusercontent.com/40860137/96006591-38fa8400-0e70-11eb-9a40-ab80bba133a9.png)

**Comment by dsnslab** [comment]
You can use `filter` to search specific `event.code`, so you will find your events.
You can check if you run beats as admin or not.

**Comment by rreexxllii0310** [comment]
> You can use `filter` to search specific `event.code`, so you will find your events.
> You can check if you run beats as admin or not.

But, I have searched for event.code,and I still can't find it.
I always run powershell as admin

**Comment by dsnslab** [comment]
Hi,
Did you make sure you don't turn on any filter before your search?

**Comment by lilychou0105** [comment]
Hi, I have problem changing fields.hostname QQ
I already refer to #1 and above.
I have try to modified `winlogbeats.yml` and even reboot, also google a lot.
But the fields.hostname still stay default: unknown
![image](https://user-images.githubusercontent.com/72923437/96250540-8f3b0480-0fe1-11eb-8c66-43db0bf4b524.png)

I had try many different way, e.g. `name:` `hostname:` `fields.hostname:` but neither work QQ

**Comment by dsnslab** [comment]
@lilychou0105 
Your format is wrong.
You can google how to set hostname for beats.
It's hard to give you hint, since it will show the answer.

**Comment by lilychou0105** [comment]
OK, this will help. Appreciate it!!

**Comment by lilychou0105** [comment]
https://www.elastic.co/guide/en/beats/winlogbeat/current/configuration-general-options.html
I follow the setting name as the link above.
Logs on my Windows shows edited beat name to my id (is this the one same as fields.hostname?)
I also tried `beat.hostname` , but the name on Kibana still stay unknown...

**Comment by dsnslab** [comment]
I see.
**Hint: you should set fields.hostname**

**Comment by lilychou0105** [comment]
I have tried this command tens of time literately, it can't work !!
Than I finally found out the problem, which is `Stop-Service winlogbeat`.
Even I shut down the whole system, it still doesn't change.
However, after I stop and restart again, it finally changed QQQQ

**Comment by yamiefun** [comment]
Hi @dsnslab 
I've tried to use windows event viewer to see the logs, but it seems that it can't get "file system" log even I've tried to create or delete files. Do I miss any necessary setting? Thanks for suggestions.
<img width="572" alt="截圖 2020-10-18 下午4 49 23" src="https://user-images.githubusercontent.com/34006713/96362720-e1a32f00-1161-11eb-81a2-d95bb4f52f48.png">

**Comment by lilychou0105** [comment]
@yamiefun 
Hi, you can google `track file on windows`. Then you will find really useful information about setting windows to get these logs.

**Comment by afcidk** [comment]
As TAs mentioned in #9, some events are not logged by deafult, so you have to search where to enable these loggings (e.g. group policy editor).

**Comment by yamiefun** [comment]
> > I'm not sure why you have to find `secpol.msc`, but if you want, I found some [information](https://freeingcockatiel.blogspot.com/2016/09/windows10-secpolmsc.html) about it.
> > It might help you.
> > You **don't** have to use other beats to complete this project.
> > Maybe you can try to google `Event Viewer`.
> > There are some information about windows events, so you will know how to observe the log.
> 
> ![image](https://user-images.githubusercontent.com/40860137/96006291-e91bbd00-0e6f-11eb-80e4-431e8f49557e.png)
> 
> Now I find the create file event on `Event Viewer`
> But my kibana no has log on it, and I don't know why.
> ![image](https://user-images.githubusercontent.com/40860137/96006591-38fa8400-0e70-11eb-9a40-ab80bba133a9.png)

Do anyone solve this problem? I can get file system log with windows event viewer, but can't find it on kibana. Do I need to modify settings in winlogbeat.yml or anything else? 
I'm running winlogbeat with administrator and not using any filter on kibana.

**Comment by yamiefun** [comment]
@lilychou0105  Thanks very much for help. Do you have any idea about how to track an application usage? I've tried the same ways as tracking a file but I don't think it's the right way to answer scenario (e) or (f).

**Comment by lilychou0105** [comment]
@yamiefun  #1 had mention there's something to be audited (there's a link provided, the content is quiet clear). It's very similar to tracking a file.

**Comment by yamiefun** [comment]
@lilychou0105 Thanks very much. Solve this problem in less than 1 min lol.
