### ISSUE TITLE
winlogbeat secure module not support event 4802-4803 4667-4668 

### ISSUE THREAD

**Issue by powgo377** [dsnslab/NetworkSecurity#9]
official docs : 
https://www.elastic.co/guide/en/beats/winlogbeat/current/winlogbeat-module-security.html

I think 4802-4803 4667-4668 is essential to this project, but winlogbeat doesn't support it,
I wonder if this is expected, 
If yes, I think I need some hints     : (      (maybe filebeat((? , I almost tried to modify and recompile winlogbeat ......)

**Comment by david9705** [comment]
I also have same problem.
event id   : information
4802:        screen saver
9999:        object rename
1621:        open calculator.exe
??:             visit website
Those logs  are in the [https://www.manageengine.com/products/active-directory-audit/kb/windows-event-log-id-list.html?tab=System](url), and cannot present in kibana.

**Comment by dsnslab** [comment]
Since those events belong to **security** in windows event viewer, you have to run winlogbeat as `admin`.
Winlogbeat can collect those events in default.

**Comment by powgo377** [comment]
I always run winlogbeat as admin to complete scenario a,b,
and still can't get 4802-4803 xxxxx,
looks like winlogbeat just not support that.

another reference here : https://github.com/elastic/beats/issues/16334
there are still working to support these event IDs.

**Comment by dsnslab** [comment]
We test screen saver now, and we use **winlogbeat version 7.9.2 in default**.
[https://www.elastic.co/downloads/beats/winlogbeat](url)

We can see related log in Kibana.
![image](https://user-images.githubusercontent.com/71757897/95941454-606f3380-0e13-11eb-887c-c1dd108f0fd9.png)

Maybe you try again!

**Comment by dsnslab** [comment]
@david9705 visit website should be **packetbeat**

**Comment by becca211137** [comment]
> I always run winlogbeat as admin to complete scenario a,b,
> and still can't get 4802-4803 xxxxx,
> looks like winlogbeat just not support that.
> 
> another reference here : [elastic/beats#16334](https://github.com/elastic/beats/issues/16334)
> there are still working to support these event IDs.

I also have this problem with 7.9.2 version, should I adjust other settings?
![image](https://user-images.githubusercontent.com/22147510/96096147-1b75fa80-0f02-11eb-9d93-55821f9388ab.png)
Otherwise, I can't observe the specified log on Event Viewer.

**Comment by dsnslab** [comment]
@becca211137 
The reason you can't observe specific logs is because you have to **audit** the specific event that you are looking for.
